CREATE SCHEMA `inforgenenses_crudw` ;

CREATE TABLE IF NOT EXISTS `inforgenenses_crudw`.`users` (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(16) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
)